# Generated by Django 6.0 on 2025-12-13 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=100)),
                ('telefono', models.CharField(help_text='Número de contacto', max_length=20)),
                ('direccion', models.TextField(blank=True, help_text='Dirección de residencia o negocio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha automática de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Cantidad de dinero que debe', max_digits=10)),
                ('descripcion', models.TextField(help_text='Detalle de qué es la deuda (ej: Fiado de mercado)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20)),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece la deuda', on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Cantidad abonada', max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, help_text='Nota opcional sobre el pago', max_length=200)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.deuda')),
            ],
        ),
    ]
